#!/usr/bin/env python3
"""Regenerate out/RANKINGS.md from the data. Never hand-edit that file."""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT = ROOT / "out"

import sys
sys.path.insert(0, str(ROOT / "scripts"))
from score import rank, top3_stability  # noqa: E402


def main():
    j = lambda n: json.loads((DATA / n).read_text())
    candidates, profiles, scores, gates = j("candidates.json"), j("profiles.json"), j("scores.json"), j("gates.json")
    by_id = {c["id"]: c for c in candidates["candidates"]}

    L = []
    w = L.append
    w("# Rankings\n")
    w("_Generated by `scripts/report.py`. Do not hand-edit._\n")
    w(f"Survey date **{candidates['_meta']['surveyed']}** · "
      f"**{len(candidates['candidates'])}** candidates · "
      f"**{sum(1 for g in gates['gates'].values() if not g['fails'])}** passed every hard filter · "
      f"**{len(scores['scores'])}** scored.\n")

    # --- plan facts -------------------------------------------------------
    w("\n## The shortlist, as plan facts\n")
    w("Tier A passed every hard filter. Tier B is pay-as-you-go, carried forward as overflow capacity.\n")
    w("\n| id | tier | entry $/mo | top $/mo | quota | best model | ctx | max out | moderation |")
    w("|---|---|---|---|---|---|---|---|---|")
    order = [cid for cid, _, _ in rank(scores, profiles["profiles"]["charter"])]
    for cid in order:
        c, e = by_id[cid], scores["scores"][cid]
        lo = f"${c['plan_floor_usd']:g}" if c["plan_floor_usd"] is not None else "PAYG"
        hi = f"${c['plan_top_usd']:g}" if c["plan_top_usd"] is not None else "—"
        q = c["quota"]
        q = q[:78] + "…" if len(q) > 78 else q
        w(f"| `{cid}` | {e['tier']} | {lo} | {hi} | {q} | {c['best_model'][:38]} | "
          f"{c['context']//1000}k | {c['max_output']//1000}k | {c['moderation']} |")

    # --- per-profile ------------------------------------------------------
    for name, p in profiles["profiles"].items():
        w(f"\n## Profile: {name} — {p['label']}\n")
        w(f"_{p['description']}_\n")
        w("\n| # | id | tier | score | " + " | ".join(profiles["criteria"]) + " |")
        w("|---|---|---|---|" + "---|" * len(profiles["criteria"]))
        for i, (cid, tier, sc) in enumerate(rank(scores, p), 1):
            e = scores["scores"][cid]
            cells = " | ".join(str(e[c]["s"]) for c in profiles["criteria"])
            w(f"| {i} | `{cid}` | {tier} | **{sc:.2f}** | {cells} |")

    # --- stability --------------------------------------------------------
    w("\n## Sensitivity: top-3 stability\n")
    w("How often each option lands in the top 3 across all five weightings. An option that "
      "wins under exactly one weighting is an artifact of that weighting; one that survives "
      "every weighting is a finding.\n")
    hits = top3_stability(scores, profiles)
    n = len(profiles["profiles"])
    w("\n| id | top-3 in |")
    w("|---|---|")
    for cid, c in sorted(hits.items(), key=lambda kv: -kv[1]):
        w(f"| `{cid}` | {c}/{n} profiles |")

    # --- eliminations -----------------------------------------------------
    w("\n## Eliminated by hard filter\n")
    by_filter = {}
    for cid, g in gates["gates"].items():
        for f in g["fails"]:
            by_filter.setdefault(f, []).append(cid)
    for f, ids in sorted(by_filter.items(), key=lambda kv: -len(kv[1])):
        w(f"\n### `{f}` — {len(ids)} candidates\n")
        w("\n| id | reason |")
        w("|---|---|")
        for cid in ids:
            w(f"| `{cid}` | {gates['gates'][cid]['reason']} |")

    OUT.mkdir(exist_ok=True)
    (OUT / "RANKINGS.md").write_text("\n".join(L) + "\n")
    print(f"wrote {OUT / 'RANKINGS.md'} ({len(L)} lines)")


if __name__ == "__main__":
    main()
