#!/usr/bin/env bash
#
# Scaffold a comparison study that runs immediately.
#
# The templates ship with three worked example candidates, so the pipeline is
# green from the first command — you replace data rather than debug wiring.
#
# Usage:  new-study.sh <study-dir>

set -euo pipefail

SKILL_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

if [[ $# -lt 1 ]]; then
  echo "usage: new-study.sh <study-dir>" >&2
  exit 2
fi

STUDY="$1"

if [[ -e "$STUDY" && -n "$(ls -A "$STUDY" 2>/dev/null)" ]]; then
  echo "refusing to scaffold into non-empty directory: $STUDY" >&2
  exit 1
fi

mkdir -p "$STUDY/data" "$STUDY/out"
cp "$SKILL_DIR/templates/dataset.json"  "$STUDY/data/dataset.json"
cp "$SKILL_DIR/templates/profiles.json" "$STUDY/data/profiles.json"
cp "$SKILL_DIR/templates/criteria.py"   "$STUDY/criteria.py"

cat > "$STUDY/.gitignore" <<'EOF'
# Generated by the scorer — regenerate with score.py rather than tracking churn.
out/*.json
out/*.csv
EOF

echo "scaffolded $STUDY"
echo
echo "next:"
echo "  1. replace _meta.reference_spec in $STUDY/data/dataset.json"
echo "  2. replace the example candidates with real ones"
echo "  3. define the criteria in $STUDY/criteria.py"
echo
echo "verify it still runs at any point:"
echo "  \${CLAUDE_SKILL_DIR}/scripts/validate.py $STUDY"
echo "  \${CLAUDE_SKILL_DIR}/scripts/score.py $STUDY --all-profiles"
