//! Launching an agent and turning its output back into events.
//!
//! The launcher is a generated bash script rather than a direct `exec`, because
//! the process has to live inside tmux to be observable. The script pipes the
//! harness through `tee`, so the same bytes reach the pane a human watches and
//! the JSONL file Jod parses.

use std::path::{Path, PathBuf};

use tokio::io::AsyncReadExt;
use tokio::sync::mpsc::UnboundedSender;

use crate::error::Result;
use crate::event::{AgentEnvelope, AgentEvent};
use crate::harness::{ArgPart, Harness, SpawnRequest};
use crate::{paths, tmux};

/// Marker the launcher appends once the harness exits, carrying its exit code.
/// The runner watches for this rather than polling the process table.
pub const EXIT_MARKER: &str = "__JOD_EXIT__:";

/// Quote a value for safe use inside single quotes in bash.
fn sq(value: &str) -> String {
    format!("'{}'", value.replace('\'', r"'\''"))
}

/// Render the launcher script.
///
/// The prompt is read from a file into `$JOD_PROMPT` and passed as `"$JOD_PROMPT"`,
/// so a prompt containing quotes, newlines or `$(...)` is never re-parsed by the
/// shell.
pub fn render_script(
    program: &Path,
    args: &[ArgPart],
    cwd: &Path,
    prompt_file: &Path,
    stream_file: &Path,
    agent_name: &str,
) -> String {
    let argv = args
        .iter()
        .map(|a| match a {
            ArgPart::Literal(s) => sq(s),
            ArgPart::Prompt => "\"$JOD_PROMPT\"".to_string(),
        })
        .collect::<Vec<_>>()
        .join(" ");

    format!(
        r#"#!/usr/bin/env bash
# Generated by Jod. Agent: {name}
set -o pipefail

cd {cwd} || exit 127
JOD_PROMPT="$(cat {prompt})"
export JOD_PROMPT

{program} {argv} 2>&1 | tee -a {stream}
code=${{PIPESTATUS[0]}}

printf '{marker}%s\n' "$code" >> {stream}
echo
echo "[jod] agent {name_q} exited with code $code"
echo "[jod] this session stays open on purpose — see docs/jod-system.md."
echo "[jod] close it with Ctrl-D, or from Jod's Kill button."

# Hand the pane a shell instead of letting the session die.
#
# A session that destroys itself takes any attached client with it
# (tmux's detach-on-destroy defaults to on), which closes the terminal
# window of anyone who was watching. Staying alive also leaves the final
# output on screen and the agent's directory ready to inspect.
exec "${{SHELL:-/bin/bash}}" -l
"#,
        name = agent_name,
        name_q = sq(agent_name),
        cwd = sq(&cwd.to_string_lossy()),
        prompt = sq(&prompt_file.to_string_lossy()),
        program = sq(&program.to_string_lossy()),
        argv = argv,
        stream = sq(&stream_file.to_string_lossy()),
        marker = EXIT_MARKER,
    )
}

/// Everything needed to talk about a launched agent.
#[derive(Debug, Clone)]
pub struct LaunchedRun {
    pub agent_id: String,
    pub tmux_session: String,
    pub stream_path: PathBuf,
}

/// Write the run's files, start its tmux session, and begin streaming events.
///
/// Returns as soon as the session is up; events arrive on `tx`.
pub async fn launch(
    agent_id: &str,
    req: &SpawnRequest,
    program: &Path,
    harness: Box<dyn Harness>,
    tx: UnboundedSender<AgentEnvelope>,
) -> Result<LaunchedRun> {
    let dir = paths::run_dir(agent_id);
    tokio::fs::create_dir_all(&dir).await?;

    let prompt_file = paths::prompt_path(agent_id);
    let stream_file = paths::stream_path(agent_id);
    let script_file = paths::script_path(agent_id);

    tokio::fs::write(&prompt_file, &req.prompt).await?;
    // Create the stream up front so the tailer never races the harness.
    tokio::fs::write(&stream_file, b"").await?;

    let script = render_script(
        program,
        &harness.args(req),
        &req.cwd,
        &prompt_file,
        &stream_file,
        &req.name,
    );
    tokio::fs::write(&script_file, script).await?;

    let session = tmux::session_name(agent_id);
    tmux::new_session(&session, &req.cwd, &script_file).await?;

    tokio::spawn(tail_stream(
        agent_id.to_string(),
        stream_file.clone(),
        session.clone(),
        harness,
        tx,
    ));

    Ok(LaunchedRun {
        agent_id: agent_id.to_string(),
        tmux_session: session,
        stream_path: stream_file,
    })
}

/// How long to keep reading after the tmux session disappears, so the tail of a
/// killed or crashed run is not lost.
const GRACE_POLLS_AFTER_SESSION_GONE: u32 = 8;
const POLL_INTERVAL: std::time::Duration = std::time::Duration::from_millis(120);

/// Follow the JSONL file, translating each line and forwarding the result.
///
/// Ends on the exit marker, or — if the session vanished without one, e.g. the
/// user killed it — after a short grace period.
async fn tail_stream(
    agent_id: String,
    stream_file: PathBuf,
    session: String,
    mut harness: Box<dyn Harness>,
    tx: UnboundedSender<AgentEnvelope>,
) {
    let mut seq = 0u64;
    let emit = |event: AgentEvent, seq: &mut u64| {
        let envelope = AgentEnvelope {
            agent_id: agent_id.clone(),
            at_ms: chrono::Utc::now().timestamp_millis(),
            seq: *seq,
            event,
        };
        *seq += 1;
        tx.send(envelope).is_ok()
    };

    let mut file = match tokio::fs::File::open(&stream_file).await {
        Ok(f) => f,
        Err(e) => {
            emit(
                AgentEvent::Error {
                    message: format!("could not read agent stream: {e}"),
                },
                &mut seq,
            );
            return;
        }
    };

    let mut pending = String::new();
    let mut buf = Vec::new();
    let mut idle_after_session_gone = 0u32;

    loop {
        buf.clear();
        let read = file.read_to_end(&mut buf).await.unwrap_or(0);
        if read > 0 {
            pending.push_str(&String::from_utf8_lossy(&buf));
        }

        let mut exit_code: Option<Option<i32>> = None;
        while let Some(idx) = pending.find('\n') {
            let line: String = pending.drain(..=idx).collect();
            let line = line.trim_end_matches(['\n', '\r']).to_string();

            if let Some(rest) = line.trim().strip_prefix(EXIT_MARKER) {
                exit_code = Some(rest.trim().parse::<i32>().ok());
                break;
            }
            for event in harness.parse_line(&line) {
                if !emit(event, &mut seq) {
                    return; // receiver dropped; nobody is listening any more
                }
            }
        }

        if let Some(code) = exit_code {
            emit(harness.finalize(code), &mut seq);
            return;
        }

        if read == 0 {
            if tmux::has_session(&session).await {
                idle_after_session_gone = 0;
            } else {
                idle_after_session_gone += 1;
                if idle_after_session_gone >= GRACE_POLLS_AFTER_SESSION_GONE {
                    emit(harness.finalize(None), &mut seq);
                    return;
                }
            }
            tokio::time::sleep(POLL_INTERVAL).await;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn script_for(args: &[ArgPart]) -> String {
        render_script(
            Path::new("/bin/claude"),
            args,
            Path::new("/work"),
            Path::new("/runs/a/prompt.txt"),
            Path::new("/runs/a/stream.jsonl"),
            "demo",
        )
    }

    #[test]
    fn the_prompt_is_passed_by_variable_never_inlined() {
        let s = script_for(&[ArgPart::lit("-p"), ArgPart::Prompt]);
        assert!(s.contains(r#"JOD_PROMPT="$(cat '/runs/a/prompt.txt')""#));
        assert!(s.contains(r#""$JOD_PROMPT""#));
    }

    #[test]
    fn a_hostile_literal_cannot_break_out_of_its_quotes() {
        let s = script_for(&[ArgPart::lit("'; rm -rf /tmp/x; echo '")]);
        assert!(!s.contains("; rm -rf /tmp/x; echo ;"));
        assert!(
            s.contains(r"'\''"),
            "single quotes must be escaped, got:\n{s}"
        );
    }

    #[test]
    fn output_is_teed_so_the_pane_and_the_log_see_the_same_bytes() {
        let s = script_for(&[ArgPart::lit("-p")]);
        assert!(s.contains("2>&1 | tee -a '/runs/a/stream.jsonl'"));
    }

    #[test]
    fn the_exit_code_is_taken_from_the_harness_not_from_tee() {
        let s = script_for(&[]);
        assert!(s.contains("${PIPESTATUS[0]}"));
        assert!(s.contains(EXIT_MARKER));
    }

    /// Regression: a session that destroys itself takes any attached client
    /// with it (tmux's `detach-on-destroy` defaults to `on`), which closed the
    /// terminal window of whoever was watching the agent.
    #[test]
    fn the_session_outlives_the_agent_so_watching_one_cannot_close_a_terminal() {
        let s = script_for(&[ArgPart::lit("-p")]);
        assert!(
            s.contains(r#"exec "${SHELL:-/bin/bash}" -l"#),
            "the pane must get a shell rather than letting the session die:\n{s}"
        );
    }

    #[test]
    fn the_exit_marker_is_written_before_the_pane_becomes_a_shell() {
        let s = script_for(&[]);
        let marker = s.find(EXIT_MARKER).expect("marker must be written");
        let exec = s.find("exec \"${SHELL").expect("shell must be exec'd");
        assert!(
            marker < exec,
            "the run must be reported finished before the pane is handed over"
        );
    }

    #[test]
    fn a_failed_chdir_aborts_rather_than_running_in_the_wrong_place() {
        let s = script_for(&[]);
        assert!(s.contains("cd '/work' || exit 127"));
    }

    #[test]
    fn paths_containing_spaces_stay_one_argument() {
        let s = render_script(
            Path::new("/opt/my tools/claude"),
            &[],
            Path::new("/my work"),
            Path::new("/r/p.txt"),
            Path::new("/r/s.jsonl"),
            "n",
        );
        assert!(s.contains("'/opt/my tools/claude'"));
        assert!(s.contains("cd '/my work'"));
    }
}
