#!/usr/bin/env python3
"""Generate out/RANKINGS.md for the IP-blocking study.

Owns every number in the report so the tables cannot drift from the dataset.
The judgement lives in REPORT.md, written by hand.

Usage:  python3 report.py [--trials 20000]
"""

import argparse
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL = os.path.join(HERE, "..", "..", ".agents", "skills", "compare-options")
SCORE = os.path.join(SKILL, "scripts", "score.py")
OUT = os.path.join(HERE, "out")

PROFILES = ["jod", "cheapest", "max-success", "ethical"]
ALL_LAYERS = ["tls", "http2", "js", "behavior", "ip_rep", "captcha"]

CONF = {"high": "**high**", "medium": "medium", "low": "_low_"}


def run(profile, trials):
    path = os.path.join(OUT, f"scores-{profile}.json")
    subprocess.run([sys.executable, SCORE, HERE, "--profile", profile,
                    "--trials", str(trials), "--json", path,
                    "--csv", os.path.join(OUT, f"scores-{profile}.csv"), "--quiet"],
                   check=True)
    with open(path) as fh:
        return json.load(fh)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--trials", type=int, default=20000)
    args = ap.parse_args()

    with open(os.path.join(HERE, "data", "dataset.json")) as fh:
        dataset = json.load(fh)
    by_id = {c["id"]: c for c in dataset["candidates"]}

    res = {p: run(p, args.trials) for p in PROFILES}
    jod = res["jod"]

    # --- main ranking
    rows = ["| # | Solution | $/mo | Score | Success | Layers | Cost | Ethics | Top-5 | Conf |",
            "|---:|---|---:|---:|---:|---:|---:|---:|---:|---|"]
    for i, r in enumerate(jod["ranking"], 1):
        c = by_id[r["id"]]
        s = r["subscores"]
        layers = f"{len(c.get('layers_fixed', []))}/6"
        rows.append(
            f"| {i} | {r['name']} | ${r['display'].get('monthly_usd', 0):.2f} | {r['total']:.1f} | "
            f"{c['success_pct']}% | {layers} | {s['cost']:.0f} | {s['ethics']:.0f} | "
            f"{r['stability']['top_n_pct']:.0f}% | {CONF[r['confidence']]} |")
    ranking_table = "\n".join(rows)

    # --- profile comparison
    cmp_rows = ["| Rank | " + " | ".join(res[p]["profile_label"] for p in PROFILES) + " |",
                "|---:|" + "---|" * len(PROFILES)]
    for i in range(5):
        cells = []
        for p in PROFILES:
            rk = res[p]["ranking"]
            if i < len(rk):
                cells.append(f"{rk[i]['name']} (${rk[i]['display'].get('monthly_usd', 0):.0f})")
            else:
                cells.append("—")
        cmp_rows.append(f"| {i+1} | " + " | ".join(cells) + " |")
    compare_table = "\n".join(cmp_rows)

    # --- layer coverage by category
    cats = {}
    for c in dataset["candidates"]:
        cat = c["category"]
        cats.setdefault(cat, []).append(len(c.get("layers_fixed", [])))
    layer_rows = ["| Category | Typical layers fixed | Reading |", "|---|---:|---|"]
    reading = {
        "baseline": "the starting point — fails before the IP is even considered",
        "datacenter": "changes nothing Cloudflare scores",
        "residential": "fixes the IP only; the TLS handshake still gives you away",
        "isp": "fixes the IP only, but flat-rate and consented",
        "mobile": "fixes the IP only, at the highest trust level available",
        "self-hosted": "fixes the client fingerprint; add an IP source for the rest",
        "browser-infra": "managed client fingerprint, IP sometimes billed separately",
        "unblocker-api": "the whole chain, priced per request",
    }
    for cat in ["baseline", "datacenter", "residential", "isp", "mobile",
                "self-hosted", "browser-infra", "unblocker-api"]:
        if cat not in cats:
            continue
        vals = cats[cat]
        avg = sum(vals) / len(vals)
        layer_rows.append(f"| {cat} | {avg:.1f} / 6 | {reading.get(cat, '')} |")
    layer_table = "\n".join(layer_rows)

    # --- rejected
    rej = ["| Solution | Disqualified because |", "|---|---|"]
    for r in jod["rejected"]:
        rej.append(f"| {r['name']} | {r['reason']} |")
    rejected_table = "\n".join(rej)

    # --- confidence
    counts = {"high": 0, "medium": 0, "low": 0}
    for c in dataset["candidates"]:
        counts[c["confidence"]] += 1
    total = sum(counts.values())
    conf_rows = ["| Confidence | Rows | Share |", "|---|---:|---:|"]
    for k in ["high", "medium", "low"]:
        conf_rows.append(f"| {CONF[k]} | {counts[k]} | {100*counts[k]/total:.0f}% |")
    conf_table = "\n".join(conf_rows)

    w = jod["weights"]
    weights_md = "\n".join(f"- **{k}** — {v*100:.0f}%"
                           for k, v in sorted(w.items(), key=lambda kv: -kv[1]) if v > 0)

    md = f"""<!-- GENERATED by report.py — do not edit by hand.
     Narrative and recommendation live in REPORT.md. -->

# IP-blocking solutions — generated tables

{dataset['_meta']['reference_spec']}

{jod['counts']['total']} candidates, {jod['counts']['eligible']} eligible after filters.
Monte Carlo: {args.trials:,} trials perturbing **success rate** (not price) by each
row's confidence, plus weights +/-35%.

## Weighting — Jod profile

{weights_md}

## Full ranking — Jod profile

{ranking_table}

"Layers" is how many of Cloudflare's six checks (TLS, HTTP/2, JS challenge,
behaviour, IP reputation, CAPTCHA) the solution addresses. It is the column
that explains most of the surprises in this table.

## What wins under different priorities

{compare_table}

## Layer coverage by category

{layer_table}

## Filtered out before scoring

{rejected_table}

## Data confidence

{conf_table}

Rows marked `composed-estimate` are stacks whose success rate was inferred by
combining two separately-measured components. No benchmark tested those
pairings; they are the study's central recommendation *and* its least certain
numbers, which is why the Monte Carlo perturbs them hardest.
"""

    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, "RANKINGS.md"), "w") as fh:
        fh.write(md)

    print("wrote out/RANKINGS.md")
    for p in PROFILES:
        top = res[p]["ranking"][0]
        print(f"  {p:<12} winner: {top['name']} "
              f"(${top['display'].get('monthly_usd', 0):.2f}, {top['total']:.1f})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
