#!/usr/bin/env python3
"""Regenerate out/RANKINGS.md from the raw benchmark output and the scores.

Never hand-edit out/RANKINGS.md — edit the data and rerun:

    python3 scripts/report.py
"""

import json
import os
import statistics
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "out")
DATA = os.path.join(ROOT, "data")

import score as scoring  # noqa: E402  (same directory)


def load_results():
    p = os.path.join(OUT, "raw-results.jsonl")
    if not os.path.exists(p):
        return []
    rows = []
    with open(p) as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    rows.append(json.loads(line))
                except json.JSONDecodeError:
                    pass
    return rows


def md_table(headers, rows):
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]
    for r in rows:
        out.append("| " + " | ".join("" if c is None else str(c) for c in r) + " |")
    return "\n".join(out)


def fmt(v, suffix=""):
    return "—" if v is None else f"{v}{suffix}"


def main():
    res = load_results()
    parts = ["# Rankings and measurements", "", "*Generated by `scripts/report.py`. Do not hand-edit.*", ""]

    host = (
        "Measured inside Docker Linux containers (aarch64) on a 4 vCPU / 8 GB VM — "
        "chosen to approximate a small VPS. Servers and the benchmark client share that budget, "
        "as they would on a real single-box deployment."
    )
    parts += ["## Test bed", "", host, ""]

    # ---- correctness first: it is a gate, not a score --------------------
    rmw = [r for r in res if r.get("workload") == "rmw" and "write" in r]
    if rmw:
        rows = []
        for r in sorted(rmw, key=lambda r: -r["write"]["throughput_ops_s"]):
            c = r.get("correctness", {})
            lost = c.get("lost_updates", 0) or 0
            verdict = c.get("verdict", "—")
            if lost:
                verdict = f"**{verdict}** ({lost} of {c.get('expected')})"
            rows.append(
                [
                    f"`{r['db']}`",
                    r["write"]["throughput_ops_s"],
                    fmt(r["write"]["p50_ms"]),
                    fmt(r["write"]["p99_ms"]),
                    f"{r['write']['error_rate_pct']}%",
                    verdict,
                ]
            )
        parts += [
            "## Correctness under contention (the discriminator)",
            "",
            "8 writer processes, 4 hot keys, read-modify-write `+1`. "
            "Every engine was asked to do the same unsafe-looking thing; the question is what it does about it.",
            "",
            md_table(
                ["engine", "ops/s", "p50 ms", "p99 ms", "error rate", "correctness"], rows
            ),
            "",
            "> Read the last two columns together. A high error rate with a `CORRECT` verdict means the "
            "engine **refused** work it could not do safely — that is the good failure. A 0% error rate "
            "next to `LOST UPDATES` means it accepted every write and silently discarded some.",
            "",
            "*These runs were measured on the busy host, so the ops/s column is depressed by ~2-3x "
            "relative to the append table. The correctness column is unaffected — losing an update "
            "is not a performance characteristic.*",
            "",
        ]

    # ---- append scaling ---------------------------------------------------
    app = [r for r in res if r.get("workload") == "append" and "write" in r]
    if app:
        # a cell may have been measured more than once; use the median so a
        # single run stolen by a co-tenant process cannot set the headline
        quiet = [r for r in app if r.get("pass") != "contended"]
        contended = [r for r in app if r.get("pass") == "contended"]
        cells = defaultdict(list)
        widths = sorted({r["writers"] for r in quiet})
        for r in quiet:
            cells[(r["db"], r["writers"])].append(r["write"])

        def med(vals, key):
            xs = sorted(v[key] for v in vals if v.get(key) is not None)
            return statistics.median(xs) if xs else None

        dbs = sorted({db for db, _ in cells}, key=lambda db: -max(
            med(cells[(db, w)], "throughput_ops_s") or 0 for w in widths if (db, w) in cells
        ))
        rows = []
        for db in dbs:
            row = [f"`{db}`"]
            for w in widths:
                vals = cells.get((db, w))
                if not vals:
                    row.append("—")
                    continue
                t = med(vals, "throughput_ops_s")
                row.append(f"{t:,.0f}" + (f" ×{len(vals)}" if len(vals) > 1 else ""))
            allv = [v for w in widths for v in cells.get((db, w), [])]
            row.append(fmt(min(v["p50_ms"] for v in allv if v["p50_ms"] is not None)))
            row.append(f"{max(v['error_rate_pct'] for v in allv)}%")
            rows.append(row)
        parts += [
            "## Append throughput vs writer count",
            "",
            "Agent event-stream appends, ops/s, on an otherwise-idle host. Median where a cell was "
            "measured more than once (`×n` marks how many observations). The *shape* of each row — "
            "flat, rising, or collapsing — is the finding; see measurement noise below for the error bar.",
            "",
            md_table(
                ["engine"] + [f"{w} writer{'s' if w > 1 else ''}" for w in widths] + ["best p50 ms", "max err"],
                rows,
            ),
            "",
        ]

        # ---- noise ---------------------------------------------------------
        rep = {k: v for k, v in cells.items() if len(v) > 1}
        if rep:
            nrows = []
            for (db, w), vals in sorted(rep.items()):
                ts = sorted(v["throughput_ops_s"] for v in vals)
                spread = (max(ts) - min(ts)) / statistics.median(ts) * 100
                nrows.append(
                    [
                        f"`{db}`",
                        w,
                        len(ts),
                        f"{min(ts):,.0f}",
                        f"{statistics.median(ts):,.0f}",
                        f"{max(ts):,.0f}",
                        f"±{spread/2:.0f}%",
                    ]
                )
            parts += [
                "## Measurement noise",
                "",
                "The same cell, repeated on the idle host. This is the error bar on every "
                "throughput number above.",
                "",
                md_table(["engine", "writers", "runs", "min", "median", "max", "spread"], nrows),
                "",
            ]

        # contended vs quiet: the same cells measured while a co-tenant ate the CPU
        if contended:
            ccells = defaultdict(list)
            for r in contended:
                ccells[(r["db"], r["writers"])].append(r["write"]["throughput_ops_s"])
            crows = []
            for (db, w), vals in sorted(ccells.items()):
                q = cells.get((db, w))
                if not q:
                    continue
                qm = statistics.median(v["throughput_ops_s"] for v in q)
                cm = statistics.median(vals)
                crows.append([f"`{db}`", w, f"{cm:,.0f}", f"{qm:,.0f}", f"{qm/cm:.1f}x"])
            if crows:
                parts += [
                    "### The same benchmark on a busy host",
                    "",
                    "Part of the sweep ran while an unrelated container held ~177% CPU of 4 cores "
                    "(and the Docker daemon crashed once under the load). Those runs are kept and "
                    "labelled rather than discarded, because a cheap VPS is an oversubscribed, "
                    "noisy-neighbour environment by definition — this is what that costs.",
                    "",
                    md_table(["engine", "writers", "busy host", "idle host", "penalty"], crows),
                    "",
                    "> Throughput fell by roughly 2-3x across the board, and **the ranking did not "
                    "change**. Contention scales everything down together; it does not reorder the "
                    "engines. Absolute ops/s on a shared VPS should be discounted accordingly.",
                    "",
                ]

    # ---- mixed ------------------------------------------------------------
    mix = [r for r in res if r.get("workload") == "mixed" and "read" in r]
    if mix:
        rows = []
        for r in sorted(mix, key=lambda r: r["read"]["p50_ms"] or 0):
            rows.append(
                [
                    f"`{r['db']}`",
                    f"{r['write']['throughput_ops_s']:,.0f}",
                    fmt(r["write"]["p50_ms"]),
                    f"{r['read']['throughput_ops_s']:,.0f}",
                    fmt(r["read"]["p50_ms"]),
                    fmt(r["read"]["p99_ms"]),
                ]
            )
        parts += [
            "## Reads under concurrent write load",
            "",
            "4 writer processes appending while 4 reader processes query recent events.",
            "",
            md_table(
                ["engine", "write ops/s", "write p50", "read ops/s", "read p50", "read p99"], rows
            ),
            "",
        ]

    # ---- vector -----------------------------------------------------------
    # only the corrected methodology (clustered data + recall@1) is reported
    vec = [r for r in res if r.get("workload") == "vector" and "recall_at_1_pct" in r]
    if vec:
        rows = []
        for r in sorted(vec, key=lambda r: r["p50_ms"]):
            rows.append(
                [
                    f"`{r['db']}`",
                    r.get("index", "—"),
                    fmt(r.get("load_s"), " s"),
                    fmt(r.get("index_build_s"), " s"),
                    fmt(r.get("p50_ms")),
                    fmt(r.get("qps_single_thread")),
                    f"{r.get('recall_at_1_pct')}%",
                    f"{r.get('recall_at_10_pct')}%",
                ]
            )
        n = vec[0].get("n_vectors")
        parts += [
            "## Vector recall",
            "",
            f"{n:,} vectors x 384 dimensions, top-10, cosine, single-threaded. Data is "
            "**clustered** (300 centers), because 384-dimensional uniform random vectors are all "
            "nearly equidistant — against uniform data every ANN index scores near-zero recall, "
            "which measures the generator rather than the engine. Recall is against exact cosine "
            "on the same data.",
            "",
            md_table(
                ["engine", "index", "load", "index build", "p50 ms", "qps", "recall@1", "recall@10"],
                rows,
            ),
            "",
            "> `recall@1` — did it find the single true nearest neighbour — is the number that "
            "matters for agent recall, where one strongly-matching memory is usually the point. "
            "`recall@10` punishes an index for reordering near-ties that are all equally good answers.",
            "",
        ]

    # ---- weighted rankings -------------------------------------------------
    candidates = scoring.load("candidates.json")["candidates"]
    gates = scoring.load("gates.json")["gates"]
    profiles = scoring.load("profiles.json")
    try:
        scores = scoring.load("scores.json")["scores"]
    except FileNotFoundError:
        scores = {}

    kept, dropped = scoring.survivors(candidates, gates)
    parts += [
        "## Hard filters",
        "",
        f"**{len(candidates)} options considered → {len(kept)} survive → {len(dropped)} eliminated.**",
        "",
        "Eliminated options are not bad options; they fail a requirement that no amount of speed compensates for.",
        "",
        md_table(
            ["option", "why it is out"],
            [[c["name"], why[:150]] for c, why in dropped],
        ),
        "",
    ]

    if scores:
        for pname, prof in profiles["profiles"].items():
            rows_r = scoring.rank(kept, scores, prof["weights"])
            stab = scoring.sensitivity(kept, scores, prof["weights"])
            parts += [
                f"## Ranking — {pname}",
                "",
                f"*{prof['description']}*",
                "",
                md_table(
                    ["#", "option", "score", "top-3 stability"],
                    [
                        [i, r["name"], f"{r['score']:.2f}", f"{stab.get(r['id'], 0.0)}%"]
                        for i, r in enumerate(rows_r, 1)
                    ],
                ),
                "",
            ]
        parts += [
            "> **Top-3 stability** is how often an option stays in the top three across 2,000 runs "
            "with the weights jittered by ±1 and every *judged* (not measured) score jittered by ±0.5. "
            "A high score with low stability means the ranking, not the option, is doing the work.",
            "",
        ]

    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, "RANKINGS.md"), "w") as f:
        f.write("\n".join(parts))
    print(f"wrote {os.path.join(OUT, 'RANKINGS.md')} ({len(res)} raw results)")


if __name__ == "__main__":
    main()
